spring:
  cloud:
    gateway:
      routes:
      - id: PaymentService
        uri: lb://PaymentService/
        predicates:
        - Path=/payment/**
      - id: OrderService
        uri: lb://OrderService/
        predicates:
        - Path=/order/**